/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivacyPolicyRouteImport } from './routes/PrivacyPolicy'
import { Route as TermsAndConditionsRouteImport } from './routes/TermsAndConditions'
import { Route as HardscapeRouteImport } from './routes/hardscape'
import { Route as KatAndAdamRouteImport } from './routes/katAndAdam'
import { Route as PalmettoRouteImport } from './routes/palmetto'
import { Route as SaritaRouteImport } from './routes/sarita'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/PrivacyPolicy',
  path: '/PrivacyPolicy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/TermsAndConditions',
  path: '/TermsAndConditions',
  getParentRoute: () => rootRouteImport,
} as any)
const HardscapeRoute = HardscapeRouteImport.update({
  id: '/hardscape',
  path: '/hardscape',
  getParentRoute: () => rootRouteImport,
} as any)
const KatAndAdamRoute = KatAndAdamRouteImport.update({
  id: '/katAndAdam',
  path: '/katAndAdam',
  getParentRoute: () => rootRouteImport,
} as any)
const PalmettoRoute = PalmettoRouteImport.update({
  id: '/palmetto',
  path: '/palmetto',
  getParentRoute: () => rootRouteImport,
} as any)
const SaritaRoute = SaritaRouteImport.update({
  id: '/sarita',
  path: '/sarita',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/PrivacyPolicy': typeof PrivacyPolicyRoute
  '/TermsAndConditions': typeof TermsAndConditionsRoute
  '/hardscape': typeof HardscapeRoute
  '/katAndAdam': typeof KatAndAdamRoute
  '/palmetto': typeof PalmettoRoute
  '/sarita': typeof SaritaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/PrivacyPolicy': typeof PrivacyPolicyRoute
  '/TermsAndConditions': typeof TermsAndConditionsRoute
  '/hardscape': typeof HardscapeRoute
  '/katAndAdam': typeof KatAndAdamRoute
  '/palmetto': typeof PalmettoRoute
  '/sarita': typeof SaritaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/PrivacyPolicy': typeof PrivacyPolicyRoute
  '/TermsAndConditions': typeof TermsAndConditionsRoute
  '/hardscape': typeof HardscapeRoute
  '/katAndAdam': typeof KatAndAdamRoute
  '/palmetto': typeof PalmettoRoute
  '/sarita': typeof SaritaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/PrivacyPolicy'
    | '/TermsAndConditions'
    | '/hardscape'
    | '/katAndAdam'
    | '/palmetto'
    | '/sarita'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/PrivacyPolicy'
    | '/TermsAndConditions'
    | '/hardscape'
    | '/katAndAdam'
    | '/palmetto'
    | '/sarita'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/PrivacyPolicy'
    | '/TermsAndConditions'
    | '/hardscape'
    | '/katAndAdam'
    | '/palmetto'
    | '/sarita'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  HardscapeRoute: typeof HardscapeRoute
  KatAndAdamRoute: typeof KatAndAdamRoute
  PalmettoRoute: typeof PalmettoRoute
  SaritaRoute: typeof SaritaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/PrivacyPolicy': {
      id: '/PrivacyPolicy'
      path: '/PrivacyPolicy'
      fullPath: '/PrivacyPolicy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/TermsAndConditions': {
      id: '/TermsAndConditions'
      path: '/TermsAndConditions'
      fullPath: '/TermsAndConditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hardscape': {
      id: '/hardscape'
      path: '/hardscape'
      fullPath: '/hardscape'
      preLoaderRoute: typeof HardscapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/katAndAdam': {
      id: '/katAndAdam'
      path: '/katAndAdam'
      fullPath: '/katAndAdam'
      preLoaderRoute: typeof KatAndAdamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/palmetto': {
      id: '/palmetto'
      path: '/palmetto'
      fullPath: '/palmetto'
      preLoaderRoute: typeof PalmettoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sarita': {
      id: '/sarita'
      path: '/sarita'
      fullPath: '/sarita'
      preLoaderRoute: typeof SaritaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  HardscapeRoute: HardscapeRoute,
  KatAndAdamRoute: KatAndAdamRoute,
  PalmettoRoute: PalmettoRoute,
  SaritaRoute: SaritaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
